version: "3.7"
services:
  jenkins:
    # image: jenkins/jenkins:jdk11
    build: .
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    environment:
      - DOCKER_HOST=host.docker.internal:2375
      - DOCKER_TLS_CERTDIR=/certs
    depends_on:
      - dind
  dind:
    image: docker:dind
    privileged: true
    user: root
    volumes:
      # - ~/jenkins:/var/jenkins_home
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/local/bin/docker:/usr/local/bin/docker
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    environment:
      - DOCKER_TLS_CERTDIR=/certs
volumes:
  jenkins-data: {}
  jenkins-docker-certs: {}
